version: "3.9"

services:
  # =====================
  # 🗄️ Base de datos
  # =====================
  db:
    image: postgres:15-alpine
    container_name: sv_db
    environment:
      POSTGRES_DB: svdb
      POSTGRES_USER: sv
      POSTGRES_PASSWORD: svpass
    volumes:
      - sv_pgdata:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d
      - uploads_data:/data/uploads
    ports:
      - "5432:5432"
    networks:
      - sv_net

  # =====================
  # 📬 SMTP para pruebas
  # =====================
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: sv_mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI
    networks:
      - sv_net

    # =====================
  # 🚦 API Ingreso (Nest principal)
  # =====================
  api:
    container_name: sv_api
    build: ./backend
    command: sh -lc "chown -R node:node /data || true ; node dist/main.js"
    stdin_open: true
    tty: true
    environment:
      # --- Core ---
      INTERNAL_API_TOKEN: super-secret-32
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://sv:svpass@db:5432/svdb
      JWT_SECRET: ${JWT_SECRET:-change-me}
      PWD_SALT: ${PWD_SALT:-sv}
      DATA_DIR: /data
      UPLOAD_DIR: /data/uploads
      TEMPLATE_DIR: /app/templates

      # --- SMTP ---
      SMTP_HOST: sv_mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: "false"
      SMTP_USER:
      SMTP_PASS:
      MAIL_FROM: "Municipalidad <no-reply@seguridadvial.local>"

      # --- API interna ---
      INTERNAL_API_BASE: http://sv_api:3000/api

      # --- Debug PDF (notificaciones) ---
      NOTIF_DEBUG_GRID: "true"
      NOTIF_PHOTO_X_MM: 102
      NOTIF_PHOTO_Y_MM: 70
      NOTIF_PHOTO_W_MM: 100
      NOTIF_PHOTO_H_MM: 75

      # =====================================================
      # 🧾 Actas Presenciales (Ticket PNG - Zebra ZQ520)
      # =====================================================
      # Template PNG: 832×1949px, 203ppi, grayscale
      PRES_TPL_PNG: /app/templates/acta-presencial-template.png
      PRES_PNG_DIR: /data/pngs-presenciales

      # Coordenadas en milímetros (convertidas a pixels: 1mm = 8px @ 203dpi)
      PRES_ACTA_X_MM: 50
      PRES_ACTA_Y_MM: 35 

      PRES_FECHA_X_MM: 20
      PRES_FECHA_Y_MM: 35 
      # PRES_HORA_X_MM: 60 
      # PRES_HORA_Y_MM: 25 

      PRES_DOMINIO_X_MM: 20 
      PRES_DOMINIO_Y_MM: 65

      PRES_CONDUCTOR_NOMBRE_X_MM: 20
      PRES_CONDUCTOR_NOMBRE_Y_MM: 43
      PRES_CONDUCTOR_DNI_X_MM: 60
      PRES_CONDUCTOR_DNI_Y_MM: 43
      PRES_CONDUCTOR_DOM_X_MM: 60
      PRES_CONDUCTOR_DOM_Y_MM: 50

      # Licencia conductor: número y clase SEPARADOS
      PRES_CONDUCTOR_LIC_NRO_X_MM: 20
      PRES_CONDUCTOR_LIC_NRO_Y_MM: 50
      PRES_CONDUCTOR_LIC_CLASE_X_MM: 65
      PRES_CONDUCTOR_LIC_CLASE_Y_MM: 56

      # Ubicación del conductor (manual, puede diferir del titular)
      PRES_CONDUCTOR_CP_X_MM: 20
      PRES_CONDUCTOR_CP_Y_MM: 10
      PRES_CONDUCTOR_DEPTO_X_MM: 20
      PRES_CONDUCTOR_DEPTO_Y_MM: 56
      PRES_CONDUCTOR_PROV_X_MM: 36
      PRES_CONDUCTOR_PROV_Y_MM: 56

      # Titular (datos del propietario del vehículo desde padrón)
      PRES_TITULAR_NOMBRE_X_MM: 20
      PRES_TITULAR_NOMBRE_Y_MM: 71
      PRES_TITULAR_DNI_X_MM: 60
      PRES_TITULAR_DNI_Y_MM: 65
      PRES_TITULAR_DOMICILIO_X_MM: 60
      PRES_TITULAR_DOMICILIO_Y_MM: 71
      PRES_TITULAR_CP_X_MM: 88
      PRES_TITULAR_CP_Y_MM: 76
      PRES_TITULAR_DEPTO_X_MM: 20
      PRES_TITULAR_DEPTO_Y_MM: 76
      PRES_TITULAR_PROV_X_MM: 50
      PRES_TITULAR_PROV_Y_MM: 76

      PRES_VEH_TIPO_X_MM: 85
      PRES_VEH_TIPO_Y_MM: 80
      PRES_VEH_MARCA_X_MM: 20
      PRES_VEH_MARCA_Y_MM: 80
      PRES_VEH_MODELO_X_MM: 50
      PRES_VEH_MODELO_Y_MM: 80

      # Tipo de infracción y lugar
      # PRES_TIPO_INF_X_MM: 20
      # PRES_TIPO_INF_Y_MM: 88
      # PRES_LUGAR_X_MM: 20
      # PRES_LUGAR_Y_MM: 93

      # Velocidades
      PRES_VEL_MEDIDA_X_MM: 20
      PRES_VEL_MEDIDA_Y_MM: 93
      # PRES_VEL_LIMITE_X_MM: 60
      # PRES_VEL_LIMITE_Y_MM: 100

      # 🎯 Datos cinemáticos (TruCam II)
      PRES_CINE_MARCA_X_MM: 20
      PRES_CINE_MARCA_Y_MM: 112
      PRES_CINE_MODELO_X_MM: 60
      PRES_CINE_MODELO_Y_MM: 112
      PRES_CINE_SERIE_X_MM: 20
      PRES_CINE_SERIE_Y_MM: 116
      PRES_CINE_APROB_X_MM: 65
      PRES_CINE_APROB_Y_MM: 116

      # Remitido a
      PRES_REMITIDO_A_X_MM: 85
      PRES_REMITIDO_A_Y_MM: 35

      # Observaciones
      PRES_OBSERVACIONES_X_MM: 20
      PRES_OBSERVACIONES_Y_MM: 125

      # Debug: activar grilla de coordenadas en PNG
      PRES_DEBUG_GRID: "true"

    depends_on:
      - db
      - mailhog
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/data/uploads
      - ./backend/templates:/app/templates:ro
      - sv_data:/data
    networks:
      - sv_net


  # =====================
  # 🔎 API ConsultasSV
  # =====================
  consultas_api:
    container_name: consultas_api
    build: ./ConsultasSV/backend
    stdin_open: true
    tty: true
    environment:
      INTERNAL_API_BASE: http://sv_api:3000/api
      INTERNAL_API_TOKEN: super-secret-32
      NODE_ENV: production
      PORT: 3000

      DATABASE_URL: postgres://sv:svpass@db:5432/svdb
      PGHOST: db
      PGPORT: 5432
      PGUSER: sv
      PGPASSWORD: svpass
      PGDATABASE: svdb

      DATA_DIR: /data
      UPLOAD_DIR: /data/uploads

      SMTP_HOST: sv_mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: "false"
      SMTP_USER:
      SMTP_PASS:
      MAIL_FROM: "Municipalidad <no-reply@seguridadvial.local>"

      JWT_SECRET: change-me
      PWD_SALT: sv

    depends_on:
      - db
      - mailhog
    restart: unless-stopped
    volumes:
      - uploads_data:/data/uploads
      - sv_data:/data
      # ⬇️ ANTES: ./_empty:/app/sql:ro
      # ⬆️ Eso ocultaba los scripts y no migraba nada
      - ./backend/sql:/app/sql:ro   # ✅ ahora sí verá 001_*.sql, 002_*.sql, etc.
    networks:
      - sv_net


  # =====================
  # 🌐 Web (Nginx)
  # =====================
  web:
    container_name: sv_web
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
      - consultas_api
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: C:\Users\felip\Proyecto\seguridad-vial-docker-clean\ConsultasSV\frontend\dist
        target: /usr/share/nginx/html/consultas
        read_only: true
    networks:
      - sv_net

# =====================
# 📦 Volúmenes y red
# =====================
volumes:
  sv_pgdata:
  uploads_data:
  sv_data:

networks:
  sv_net:
    driver: bridge
